### PR TITLE
fix a few minor formatting issues

### PR DESCRIPTION
**Pull request by joewiz**
- backtick variable names in text
- em dashes
- underline to italicize titles vs. asterisks for emphasis

### CODE REVIEW

**Comment by CliffordAnderson** [comment]
Just seeing these now. Thanks again!

**Comment by joewiz** [comment]
Ah, sure! My xquery markdown conventions have evolved since then; another PR may come along these lines (though not tonight, I promise!).

**Comment by joewiz** [comment]
Though I have a suggestion on the pig latin example, which I've added as a comment on the gist. Since gist doesn't notify authors, FYI, here's the comment: https://gist.github.com/CliffordAnderson/a1ac3141828b504ee756#gistcomment-1868881.

**Comment by CliffordAnderson** [comment]
Thanks, @joewiz! I've never used `fn:analyze-string()` but I clearly need to add it to my repertoire.

**Pull request merged**
